### PR TITLE
Preparing the viewmodels to use Dependency Injection

### PR DESCRIPTION
**Pull request by aboimpinto**
In order to test the ViewModels, they should not have access to App.xaml.cs

this will help on test ability of the viewmodels.

### CODE REVIEW

**Comment by justingaffney** [comment]
Commits da4fc55 & 30497e4 look good, but I'm not sure about some of the changes in commit c0956e9. Why couldn't you build the application with the `Any CPU` configuration? What errors were you getting?

**Comment by justingaffney** [comment]
Also in commit c0956e9 I'm not sure about commenting out the line that sets `AlgorithmName` in CertificateRequestViewModel. Have you tried generating a certificate with that line of code commented out? Because when I tried I got a `System.Runtime.InteropServices.COMException` with the message "CertEnroll::CX509PrivateKey::Import: Invalid type specified. 0x8009000a (-2146893814 NTE_BAD_TYPE)". 

Can you please check if you can generate a certificate file without any exceptions?

**Comment by aboimpinto** [comment]
if we have AnyCPU, I have errors using the leveldb. Say that leveldb has wrong format.

**Comment by justingaffney** [comment]
In commit 92a6776, I don't think the new `MessageAggregator` class is needed. There is already a class in Neo.UI.Base.MVVM called `EventAggregator` with almost identical functionality, couldn't that be injected into the ViewModels instead?

**Comment by aboimpinto** [comment]
Not at the moment ... but in the future we can rename it to align ...

I'm trying to create a side infrastructure that don't break the current one. It's easy to work with one error than errors all over the app.

**Comment by justingaffney** [comment]
The name isn't a problem, my point is a class already exists that does the same thing

**Comment by aboimpinto** [comment]
I fix all the conflicts ....

Paulo

**Review by justingaffney — APPROVED** [review]
Looks good

**Pull request merged**
