### PR TITLE
All dependencies on HomeViewModel are now injected in the constructor

### PR DESCRIPTION
**Pull request by aboimpinto**
AssetViewModel and TransactionViewModel is not injected anymore

Communication between this view models and HomeViewModel is made through messages

BlockChainController created in order to abstract LocalNode from HomeViewModel

WalletController created in order to abstract wallet access from HomeViewModel

### CODE REVIEW

**Comment by aboimpinto** [comment]
ufffaaa no conflicts and compiles

**Comment by aboimpinto** [comment]
hope that this two last commits can be added too to this PR!

**Comment by aboimpinto** [comment]
Wiring the BlockChainController it's not working 100%. For some reason, doesn't connect to any peer. I don't have the knowledge to debug this further.

**Comment by aboimpinto** [comment]
Wallet is working good. I testes the Load of a wallet and all the values are showing good.
we are in the position to start creating UnitTests for this classes.

**Review by justingaffney — APPROVED** [review]

**Pull request merged**
